downgrade torch, upgrade torchvision
downgrade to torch 2.9.0 so we can upgrade torchvision to a cuda13
build for b300 support.

otherwise the cpu version of torchvision loads, and we hit:
>  RuntimeError: No such operator torchvision::nms